#!/bin/bash
set -e

echo "=> Configuring PHP-FPM ..."

if [[ $PHP_POOL != "" ]]; then
echo "=> Custom pool name ($PHP_POOL) being used"
sed -i '/[www]/c\['$PHP_POOL']' /etc/php-fpm.d/www.conf
else
echo "=> Default pool name (www) being used"
fi
echo "=> Done!"

if [[ $PHP_PORT != "" ]]; then
echo "=> Custom port ($PHP_PORT) being used"
sed -i '/^listen/c \listen = 0.0.0.0:'$PHP_PORT'' /etc/php-fpm.d/www.conf
else
echo "=> Default port (9000) being used"
sed -i '/^listen/c \listen = 0.0.0.0:9000' /etc/php-fpm.d/www.conf
fi
echo "=> Done!"

if [[ $PHP_USER != "" ]]; then
echo "=> Custom user & group ($PHP_USER) being used"
sed -i '/^user/c \user = '$PHP_USER'' /etc/php-fpm.d/www.conf
sed -i '/^group/c \group = '$PHP_USER'' /etc/php-fpm.d/www.conf
else
echo "=> Default user & group (apache) being used"
fi
echo "=> Done!"

echo "=> Allowing listen from anywhere"
sed -i 's/^listen.allowed_clients/;listen.allowed_clients/' /etc/php-fpm.d/www.conf
echo "=> Done!"

echo "=> ... Finish configuring PHP-FPM"

exec php-fpm -F > /dev/null 2>&1