### Dockerfile
#
#   See https://github.com/russmckendrick/docker

FROM ghcr.io/russmckendrick/base:latest
LABEL maintainer="Russ McKendrick <russ@mckendrick.io>"

RUN apk add  -U apache2-utils
RUN rm -rf /var/cache/apk/*