#!/bin/bash
set -e

MYSQL_DATABASE=${MYSQL_DATABASE:-""}
MYSQL_USER=${MYSQL_USER:-""}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-""}
VOLUME_HOME="/var/lib/mysql"

chown -R mysql:mysql $VOLUME_HOME

if [[ ! -d $VOLUME_HOME/mysql ]]; then

echo "=> An empty or uninitialized MariaDB volume is detected in $VOLUME_HOME"
echo "=> Installing MariaDB ..."
mysql_install_db > /dev/null 2>&1
echo "=> Done!"  

chown -R mysql:mysql $VOLUME_HOME

PASS=${MYSQL_ROOT_PASSWORD:-$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 8)}
_word=$( [ ${MYSQL_ROOT_PASSWORD} ] && echo "user defined" || echo "random" )

echo "=> Creating MariaDB root user with ${_word} password"

/usr/sbin/runuser -u mysql /usr/libexec/mysqld > /dev/null 2>&1 &
sleep 5

tfile=`mktemp`
if [[ ! -f "$tfile" ]]; then
    return 1
fi
cat << EOF > $tfile
USE mysql;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$PASS';
FLUSH PRIVILEGES;
EOF
if [[ $MYSQL_DATABASE != "" ]]; then
    echo "CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile
    if [[ $MYSQL_USER != "" ]]; then
        echo "GRANT ALL ON \`$MYSQL_DATABASE\`.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';" >> $tfile
    fi
fi
mysql < $tfile
rm -f $tfile

if [[ $MYSQL_DATABASE != "" ]]; then
echo "=> Creating $MYSQL_DATABASE database"
    if [[ $MYSQL_USER != "" ]]; then
echo "=> Adding $MYSQL_USER user with a password of $MYSQL_PASSWORD"
    fi
fi

echo "=> Done!"
echo "========================================================================"
echo "You can now connect to this MariaDB Server using:"
echo ""
echo "    mysql -uroot -p$PASS -h<host> -P<port>"
echo ""
echo " or:"
echo ""
echo "    mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -h<host> -P<port>"
echo ""
echo "========================================================================"

else
    echo "=> Using an existing volume of MariaDB"
fi

exec mysqld_safe